### ISSUE TITLE
Adding "title" to Github Action

### ISSUE THREAD

**Issue by kubawerlos** [jaywcjlove/markdown-to-html-cli#85]
Hi,

thanks for a great tool, it works like a charm. There's one thing missing, though - would you be open to adding `title` to `action.yml`? I'd be glad to contribute.

**Comment by jaywcjlove** [comment]
https://github.com/jaywcjlove/markdown-to-html-cli/blob/abb0779083ac75815c357eb1bc06c3ac1bf6960a/action.yml#L20-L23

@kubawerlos  Welcome to contribute, add "title", which can be placed in `config`

https://github.com/jaywcjlove/markdown-to-html-cli/blob/abb0779083ac75815c357eb1bc06c3ac1bf6960a/packages/action/src/action.ts#L34-L46

**Comment by jaywcjlove** [comment]
@kubawerlos thx! Upgrade `v4.1.0`
